appname : ExampleApp
charset : UTF-8
log     : debug
logger  : console

plugins :
    UserAdmin :
        foo : bar

DBIC :
  UserAdmin :
        dsn          : dbi:SQLite:dbname=UserAdmin.db
        schema_class : ExampleApp::Schema

